export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAILURE = "USER_GET_FAILURE";

export const USER_CLEAR = "USER_CLEAR";

// export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
// export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
// export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

// export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
// export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
// export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const CATEGORIES_GET_REQUEST = "CATEGORIES_GET_REQUEST";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";

export const GAME_SET_CATEGORY = "GAME_SET_CATEGORY";
