export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAILURE = "USER_GET_FAILURE";

export const USER_CLEAR = "USER_CLEAR";

export const USER_ERROR_CLEAR = "USER_ERROR_CLEAR";

// export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
// export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
// export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

// export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
// export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
// export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const CATEGORIES_GET_REQUEST = "CATEGORIES_GET_REQUEST";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";

export const GAME_SET_CATEGORY = "GAME_SET_CATEGORY";
export const GAME_CLEAR_CATEGORY = "GAME_CLEAR_CATEGORY";

export const GAME_REWARD_POINT_REQUEST = "GAME_REWARD_POINT_REQUEST";
export const GAME_REWARD_POINT_SUCCESS = "GAME_REWARD_POINT_SUCCESS";
export const GAME_REWARD_POINT_FAILURE = "GAME_REWARD_POINT_FAILURE";

export const PICTURE_SET = "PICTURE_SET";
export const PICTURE_CLEAR = "PICTURE_CLEAR";

export const PICTURE_GET_LABELS_REQUEST = "PICTURE_GET_LABELS_REQUEST";
export const PICTURE_GET_LABELS_SUCCESS = "PICTURE_GET_LABELS_SUCCESS";
export const PICTURE_GET_LABELS_FAILURE = "PICTURE_GET_LABELS_FAILURE";

export const PICTURE_CLEAR_LABELS = "PICTURE_CLEAR_LABELS";

export const RESULT_SET = "RESULT_SET";
export const RESULT_CLEAR = "RESULT_CLEAR";
